run:
  skip-dirs-use-default: true
  allow-parallel-runners: true
  go: "1.19"

output:
  print-issued-lines: false
  print-linter-name: true
  unique-by-line: false
  sort-results: true

linters-settings:
  staticcheck:
    go: "1.19"
  govet:
    enable-all: true
    check-shadowing: false
    disable:
      - shadow
  errcheck:
    check-blank: true
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      # - security
linters:
  fast: false
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - varcheck
    # issues with generics
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    # annoying
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - ireturn
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
